// core: true인 카테고리는 카테고리 탭에서 삭제할 수 없습니다 (실수로 학습 데이터를 잃지 않도록 보호).
// 이후 카테고리 탭에서 사용자가 새로 추가하는 카테고리는 기본적으로 core: false (삭제 가능)로 생성됩니다.
const DEFAULT_CATEGORIES = [
  { key: 'realestate', label: '부동산·금융', core: true },
  { key: 'daily',      label: '일상영어', core: true },
  { key: 'business',   label: '비즈니스영어', core: true },
  { key: 'advanced',   label: '심화영어(고급 어휘)', core: true },
  { key: 'toeic',      label: '토익(TOEIC)', core: true },
  { key: 'toefl',      label: '토플(TOEFL)', core: true },
];

// 시드 콘텐츠 버전. 올릴 때마다 app.js의 syncSeedContent가 실행되어, 기존에 저장된 학습 상태(SRS 주기,
// 학습일차 등)는 보존한 채로 아래 SEED_WORDS 내용과 diff하여 새 단어 추가 / 삭제된 단어 제거 /
// 기존 단어의 뜻·예문·팁·유의어 등 콘텐츠만 최신화합니다.
const SEED_VERSION = 5;

// type: 'word' | 'phrase' (관용구/표현)
// synonyms/antonyms/collocations는 선택 항목이며, 자연스러운 경우에만 채웠습니다.
const SEED_WORDS = [
  // ---------------- 부동산 (부동산 · 거시경제 · 채권/주식/파생 리포트 중~고난도 용어) ----------------
  { term: 'appraisal', ipa: '/əˈpreɪ.zəl/', pos: '명사', type: 'word', category: 'realestate',
    meaningKo: '감정평가',
    examples: [{ en: 'The bank requires an independent appraisal before approving the loan.', ko: '은행은 대출 승인 전 독립적인 감정평가를 요구한다.' }],
    tip: '동사형은 appraise. "assessment"는 조세/일반 평가, "appraisal"은 전문적 가치평가 뉘앙스가 강합니다.',
    synonyms: ['valuation', 'assessment'], antonyms: [], collocations: ['conduct an appraisal', 'independent appraisal'] },
  { term: 'due diligence', ipa: '/djuː ˈdɪl.ɪ.dʒəns/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '실사 (거래 전 검토 절차)',
    examples: [{ en: 'We need to complete due diligence before closing the deal.', ko: '거래를 종결하기 전에 실사를 완료해야 한다.' }],
    tip: '줄여서 "DD"라고도 부릅니다. "do due diligence on X" 형태로 자주 씁니다.',
    synonyms: [], antonyms: [], collocations: ['conduct due diligence', 'due diligence process'] },
  { term: 'underwrite', ipa: '/ˈʌn.dɚ.raɪt/', pos: '동사', type: 'word', category: 'realestate',
    meaningKo: '(대출/보험) 인수심사하다',
    examples: [{ en: 'The lender will underwrite the loan based on projected cash flows.', ko: '대출기관은 예상 현금흐름을 기반으로 대출을 심사할 것이다.' }],
    tip: '명사형 underwriting은 대출/보험 심사 프로세스 전체를 지칭합니다.',
    synonyms: ['assess risk'], antonyms: [], collocations: ['underwrite a loan', 'underwriting standards'] },
  { term: 'comparable sales', ipa: '/ˈkɑːm.pɚ.ə.bəl seɪlz/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '비교사례 (comps)',
    examples: [{ en: 'We adjusted the comparable sales for differences in size and location.', ko: '규모와 입지 차이를 반영해 비교사례를 조정했다.' }],
    tip: '실무에서는 줄여서 "comps"라고 부르는 경우가 훨씬 많습니다.',
    synonyms: ['comps'], antonyms: [], collocations: ['pull comps', 'adjust the comps'] },
  { term: 'loan-to-value', ipa: '/loʊn tuː ˈvæl.juː/', pos: '명사구(약어 LTV)', type: 'phrase', category: 'realestate',
    meaningKo: '담보인정비율 (LTV)',
    examples: [{ en: 'Most lenders cap the loan-to-value ratio at 65% for this asset class.', ko: '대부분의 대출기관은 이 자산군에 대해 LTV를 65%로 제한한다.' }],
    tip: '대문자 약어 LTV로 압도적으로 더 자주 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['LTV ratio', 'maximum LTV'] },
  { term: 'highest and best use', ipa: '/ˈhaɪ.ɪst ənd best juːs/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '최유효이용',
    examples: [{ en: 'The appraiser concluded that mixed-use development is the highest and best use of the site.', ko: '감정평가사는 복합용도 개발이 해당 부지의 최유효이용이라고 결론지었다.' }],
    tip: '감정평가 이론의 핵심 개념으로, 법적 허용성·물리적 가능성·경제적 타당성·최대 수익성 4요건을 충족해야 합니다.',
    synonyms: [], antonyms: [], collocations: ['highest and best use analysis'] },
  { term: 'escrow', ipa: '/ˈes.kroʊ/', pos: '명사', type: 'word', category: 'realestate',
    meaningKo: '에스크로 (제3자 예치)',
    examples: [{ en: 'The deposit is held in escrow until the transaction closes.', ko: '보증금은 거래가 종결될 때까지 에스크로에 예치된다.' }],
    tip: '"in escrow"라는 전치사구 형태로 가장 흔히 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['hold in escrow', 'escrow account', 'release from escrow'] },
  { term: 'amortization', ipa: '/əˌmɔːr.t̬əˈzeɪ.ʃən/', pos: '명사', type: 'word', category: 'realestate',
    meaningKo: '원리금 균등상환, (무형자산) 상각',
    examples: [{ en: 'The loan has a 30-year amortization schedule.', ko: '그 대출은 30년 상환 스케줄을 가지고 있다.' }],
    tip: '유형자산 감가상각은 depreciation, 무형자산/대출상환은 amortization으로 구분합니다.',
    synonyms: [], antonyms: [], collocations: ['amortization schedule', 'fully amortizing loan'] },
  { term: 'close the deal', ipa: '/kloʊz ðə diːl/', pos: '관용구', type: 'phrase', category: 'realestate',
    meaningKo: '거래를 성사시키다',
    examples: [{ en: 'Both parties finally closed the deal after months of negotiation.', ko: '수개월간의 협상 끝에 양측은 마침내 거래를 성사시켰다.' }],
    tip: '"closing"만 명사로 써서 거래 종결일 자체를 가리키기도 합니다 (e.g. "the closing is next Friday").',
    synonyms: ['seal the deal', 'finalize the transaction'], antonyms: ['walk away from the deal'], collocations: [] },
  { term: 'net operating income (NOI)', ipa: '/net ˈɑːp.ɚ.eɪ.tɪŋ ˈɪn.kʌm/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '순영업소득',
    examples: [{ en: 'The property generated $2.4 million in net operating income last year, up 6% from the prior period.', ko: '해당 자산은 작년 240만 달러의 순영업소득을 창출했으며, 이는 전기 대비 6% 증가한 수치다.' }],
    tip: 'NOI = 총운영수익 − 운영비용(감가상각·이자비용 제외). cap rate와 자산가치 산정의 출발점이 되는 핵심 지표입니다.',
    synonyms: [], antonyms: ['operating expense'], collocations: ['NOI growth', 'stabilized NOI'] },
  { term: 'going-in cap rate', ipa: '/ˈɡoʊ.ɪŋ ɪn kæp reɪt/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '매입 시점 환원율',
    examples: [{ en: 'At a 5.2% going-in cap rate, the acquisition is priced roughly in line with recent comparable transactions.', ko: '5.2%의 매입 시점 환원율로, 이번 인수는 최근 비교거래와 대체로 유사한 수준에서 가격이 책정되었다.' }],
    tip: 'exit cap rate(매각 시점 환원율)와 짝을 이루는 개념으로, 두 수치의 차이가 밸류에이션 상승/하락 가정을 좌우합니다.',
    synonyms: [], antonyms: ['exit cap rate'], collocations: [] },
  { term: 'exit cap rate', ipa: '/ˈeɡ.zɪt kæp reɪt/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '매각(출구) 시점 환원율',
    examples: [{ en: 'The model assumes a 25-basis-point expansion in the exit cap rate to account for cycle risk.', ko: '해당 모델은 사이클 리스크를 반영해 출구 환원율이 25bp 확대된다고 가정한다.' }],
    tip: 'exit cap rate를 going-in cap rate보다 높게 가정하는 것이 보수적인 밸류에이션 관행입니다.',
    synonyms: [], antonyms: ['going-in cap rate'], collocations: [] },
  { term: 'cap rate spread', ipa: '/kæp reɪt spred/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '환원율-국채금리 스프레드',
    examples: [{ en: 'As the cap rate spread over the 10-year Treasury narrowed to under 100 basis points, investors began questioning whether cap rates could compress further.', ko: '환원율과 10년 국채금리 간 스프레드가 100bp 아래로 좁혀지면서, 투자자들은 환원율이 추가로 하락할 수 있을지 의문을 갖기 시작했다.' }],
    tip: '부동산 리포트에서 금리 사이클을 논할 때 거의 항상 등장하는 개념으로, 국채금리(무위험수익률) 대비 부동산의 상대적 매력도를 보여줍니다.',
    synonyms: ['yield spread'], antonyms: [], collocations: ['spread compression', 'spread widening'] },
  { term: 'debt service coverage ratio (DSCR)', ipa: '/det ˈsɝː.vɪs ˈkʌv.ɚ.ɪdʒ ˈreɪ.ʃoʊ/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '부채상환비율',
    examples: [{ en: 'Lenders typically require a minimum DSCR of 1.25x before underwriting a loan on stabilized assets.', ko: '대출기관은 통상 안정화 자산에 대한 대출 심사 시 최소 1.25배의 DSCR을 요구한다.' }],
    tip: 'DSCR = NOI ÷ 연간 원리금상환액. 1.0배 미만이면 임대소득만으로 원리금을 감당하지 못한다는 의미입니다.',
    synonyms: [], antonyms: [], collocations: ['minimum DSCR', 'DSCR covenant'] },
  { term: 'mezzanine debt', ipa: '/ˈmez.ə.niːn det/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '메자닌 대출(중순위 대출)',
    examples: [{ en: 'The sponsor filled the capital stack gap with mezzanine debt priced at SOFR plus 650 basis points.', ko: '스폰서는 SOFR+650bp로 가격이 책정된 메자닌 대출로 자본구조상의 공백을 메웠다.' }],
    tip: '선순위 대출(senior debt)과 지분(equity) 사이에 위치하는 후순위 대출로, capital stack(자본구조) 논의에서 자주 등장합니다.',
    synonyms: [], antonyms: ['senior debt'], collocations: ['mezzanine financing', 'capital stack'] },
  { term: 'triple net lease (NNN)', ipa: '/ˈtrɪp.əl net liːs/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '삼중순임대차 (세금·보험·유지비를 임차인이 부담)',
    examples: [{ en: 'The asset is fully leased under a triple net structure, insulating the landlord from operating expense volatility.', ko: '해당 자산은 완전한 삼중순임대차 구조로 임대되어 있어, 임대인은 운영비용 변동성으로부터 보호된다.' }],
    tip: '재산세·보험료·유지관리비를 임차인이 부담하는 구조로, 리츠나 물류센터 리포트에서 자주 언급됩니다.',
    synonyms: [], antonyms: ['gross lease'], collocations: ['NNN lease structure'] },
  { term: 'sale-leaseback', ipa: '/seɪl ˈliːs.bæk/', pos: '명사', type: 'word', category: 'realestate',
    meaningKo: '세일앤리스백(매각 후 재임차)',
    examples: [{ en: 'The retailer raised $300 million through a sale-leaseback of 40 distribution centers.', ko: '그 유통업체는 물류센터 40곳에 대한 세일앤리스백을 통해 3억 달러를 조달했다.' }],
    tip: '자산을 매각하는 동시에 매수자와 장기 임대차 계약을 맺어 계속 사용하는 자금조달 기법입니다.',
    synonyms: [], antonyms: [], collocations: ['sale-leaseback transaction'] },
  { term: 'ground lease', ipa: '/ɡraʊnd liːs/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '토지임대차(대지권 임대)',
    examples: [{ en: 'The office tower sits on a 99-year ground lease, which limits its appeal to certain institutional buyers.', ko: '그 오피스 타워는 99년 토지임대차 위에 있어, 특정 기관투자자들에게는 매력이 제한적이다.' }],
    tip: '건물 소유자가 토지는 소유하지 않고 장기 임대하는 구조로, 자산 유동성과 대출 조건에 영향을 줍니다.',
    synonyms: [], antonyms: ['fee simple'], collocations: ['subject to a ground lease'] },
  { term: 'cash-on-cash return', ipa: '/kæʃ ɑːn kæʃ rɪˈtɝːn/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '현금수익률',
    examples: [{ en: 'The deal underwrites to a 7.8% cash-on-cash return in year one.', ko: '이 거래는 1년차 기준 7.8%의 현금수익률로 심사되었다.' }],
    tip: '레버리지 이후 실제 투입된 자기자본 대비 세전현금흐름 비율로, IRR과 달리 시간가치를 반영하지 않는 단순 지표입니다.',
    synonyms: ['cash yield'], antonyms: [], collocations: [] },
  { term: 'internal rate of return (IRR)', ipa: '/ɪnˈtɝː.nəl reɪt ʌv rɪˈtɝːn/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '내부수익률',
    examples: [{ en: 'The five-year business plan targets a 15% net IRR to limited partners.', ko: '5개년 사업계획은 유한책임투자자 기준 순 IRR 15%를 목표로 한다.' }],
    tip: '현금흐름의 시간가치를 반영하는 할인율 개념으로, cash-on-cash return보다 정교한 수익성 지표입니다.',
    synonyms: [], antonyms: [], collocations: ['target IRR', 'levered IRR'] },
  { term: 'stabilized asset', ipa: '/ˈsteɪ.bə.laɪzd ˈæs.et/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '안정화 자산 (안정화: 입주율이 목표 수준에 도달한 상태)',
    examples: [{ en: 'Occupancy is expected to reach stabilization by the end of next year, at which point the asset can be refinanced.', ko: '입주율은 내년 말까지 안정화 수준에 도달할 것으로 예상되며, 이 시점에 자산 재융자가 가능해진다.' }],
    tip: '일반적으로 임대율 90~95% 이상을 안정화 기준으로 봅니다. lease-up(임대 개시) 단계와 대비되는 개념입니다.',
    synonyms: ['stabilization'], antonyms: ['lease-up'], collocations: ['reach stabilization'] },
  { term: 'value-add strategy', ipa: '/ˈvæl.juː æd ˈstræt.ə.dʒi/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '밸류애드 전략(가치부가형 투자전략)',
    examples: [{ en: 'The fund pursues a value-add strategy, targeting underperforming assets that can be repositioned through renovation.', ko: '해당 펀드는 리노베이션을 통해 재포지셔닝이 가능한 저성과 자산을 타겟으로 하는 밸류애드 전략을 추구한다.' }],
    tip: 'core(안정적 우량자산) → core-plus → value-add → opportunistic 순으로 리스크와 기대수익이 높아지는 투자 스펙트럼의 한 단계입니다.',
    synonyms: [], antonyms: ['core strategy'], collocations: ['value-add opportunity'] },
  { term: 'opportunistic strategy', ipa: '/ˌɑːp.ɚ.tuːˈnɪs.tɪk ˈstræt.ə.dʒi/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '오퍼튜니스틱 전략(고위험·고수익 투자전략)',
    examples: [{ en: 'Opportunistic investors are targeting distressed office assets at steep discounts to replacement cost.', ko: '오퍼튜니스틱 투자자들은 재조달원가 대비 큰 폭으로 할인된 부실 오피스 자산을 타겟으로 하고 있다.' }],
    tip: '리스크-수익 스펙트럼에서 가장 공격적인 단계로, 개발·재포지셔닝·부실자산 등 높은 불확실성을 감수합니다.',
    synonyms: [], antonyms: ['core strategy'], collocations: [] },
  { term: 'replacement cost', ipa: '/rɪˈpleɪs.mənt kɑːst/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '재조달원가(대체원가)',
    examples: [{ en: 'The building is trading at a significant discount to replacement cost, which limits new supply risk.', ko: '그 건물은 재조달원가 대비 상당히 할인된 가격에 거래되고 있어, 신규 공급 리스크가 제한적이다.' }],
    tip: '감정평가 3방식 중 원가법의 핵심 개념이며, 신규 공급의 경제적 타당성을 가늠하는 기준으로도 쓰입니다.',
    synonyms: ['reproduction cost'], antonyms: [], collocations: ['discount to replacement cost'] },
  { term: 'functional obsolescence', ipa: '/ˈfʌŋk.ʃən.əl ˌɑːb.səˈles.əns/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '기능적 진부화',
    examples: [{ en: 'Low ceiling heights are a source of functional obsolescence for older industrial buildings.', ko: '낮은 층고는 노후 산업용 건물의 기능적 진부화 요인이다.' }],
    tip: 'economic obsolescence(경제적 진부화, 외부 요인에 의한 가치 하락)와 구분해서 씁니다.',
    synonyms: [], antonyms: [], collocations: ['economic obsolescence'] },
  { term: 'securitization', ipa: '/sɪˌkjʊr.ə.t̬əˈzeɪ.ʃən/', pos: '명사', type: 'word', category: 'realestate',
    meaningKo: '유동화(증권화)',
    examples: [{ en: 'The loan is expected to be included in a securitization pool within the next quarter.', ko: '해당 대출은 다음 분기 내 유동화 풀에 편입될 것으로 예상된다.' }],
    tip: '동사형은 securitize. CMBS, RMBS 등 자산유동화증권 발행의 기반이 되는 프로세스입니다.',
    synonyms: [], antonyms: [], collocations: ['securitization pool', 'securitize a loan'] },
  { term: 'CMBS', ipa: '/ˌsiː.em.biːˈes/', pos: '명사(약어)', type: 'word', category: 'realestate',
    meaningKo: '상업용 부동산저당증권 (Commercial Mortgage-Backed Securities)',
    examples: [{ en: 'CMBS spreads widened sharply as investors grew cautious about office loan performance.', ko: '오피스 대출 실적에 대한 투자자들의 우려가 커지며 CMBS 스프레드가 크게 확대되었다.' }],
    tip: '채권시장과 부동산시장을 잇는 대표적 상품으로, 거시 리포트에서 신용스프레드 논의와 함께 자주 등장합니다.',
    synonyms: [], antonyms: [], collocations: ['CMBS spread', 'CMBS issuance'] },
  { term: 'REIT', ipa: '/riːt/', pos: '명사(약어)', type: 'word', category: 'realestate',
    meaningKo: '리츠(부동산투자신탁)',
    examples: [{ en: 'Publicly traded REITs are pricing in a further decline in property values, trading at a discount to net asset value.', ko: '상장 리츠들은 자산가치 대비 할인된 가격에 거래되며 추가적인 자산가치 하락을 선반영하고 있다.' }],
    tip: '"net asset value(NAV)" 대비 할증/할인 여부가 리츠 밸류에이션 논의에서 핵심 지표로 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['publicly traded REIT', 'REIT dividend yield'] },
  { term: 'capital expenditure (capex)', ipa: '/ˈkæp.ə.t̬əl ɪkˈspen.dɪ.tʃɚ/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '자본적 지출',
    examples: [{ en: 'The sponsor budgeted $8 million in capex for roof replacement and mechanical upgrades.', ko: '스폰서는 지붕 교체와 설비 개선을 위해 800만 달러의 자본적 지출을 편성했다.' }],
    tip: '일상적 유지보수비(operating expense)와 달리 자산가치를 증대시키는 지출을 의미하며, NOI 계산 시 제외됩니다.',
    synonyms: [], antonyms: ['operating expense (opex)'], collocations: ['capex budget'] },
  { term: 'yield curve', ipa: '/jiːld kɝːv/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '수익률 곡선',
    examples: [{ en: 'An inverted yield curve has historically been a leading indicator of recession.', ko: '역전된 수익률 곡선은 역사적으로 경기침체의 선행지표로 여겨져왔다.' }],
    tip: '"inverted yield curve"(장단기 금리 역전)는 거시경제 리포트에서 매우 자주 등장하는 표현입니다.',
    synonyms: [], antonyms: [], collocations: ['inverted yield curve', 'steepening yield curve'] },
  { term: 'basis point (bp)', ipa: '/ˈbeɪ.sɪs pɔɪnt/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '베이시스 포인트 (0.01%p)',
    examples: [{ en: 'The Fed raised rates by 25 basis points at its latest meeting.', ko: '연준은 최근 회의에서 금리를 25bp 인상했다.' }],
    tip: '100bp = 1%p. 금리·스프레드를 논할 때 소수점 표현 대신 관용적으로 사용됩니다.',
    synonyms: [], antonyms: [], collocations: ['25 basis points', 'widen by X bp'] },
  { term: 'duration', ipa: '/dʊˈreɪ.ʃən/', pos: '명사', type: 'word', category: 'realestate',
    meaningKo: '듀레이션(채권 가격의 금리 민감도)',
    examples: [{ en: 'Long-duration bonds sold off sharply as rate-cut expectations were pushed back.', ko: '금리 인하 기대가 후퇴하면서 장기 듀레이션 채권이 급격히 매도되었다.' }],
    tip: '듀레이션이 길수록 금리 변화에 대한 가격 민감도가 커집니다. 장기 임대차가 확보된 부동산도 "채권과 유사한(bond-like)" 자산으로 비유될 때 이 개념이 함께 언급됩니다.',
    synonyms: [], antonyms: [], collocations: ['duration risk', 'long duration'] },
  { term: 'credit spread', ipa: '/ˈkred.ɪt spred/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '신용스프레드',
    examples: [{ en: 'Credit spreads on BBB-rated CMBS have widened by more than 150 basis points since the start of the year.', ko: 'BBB등급 CMBS의 신용스프레드는 연초 이후 150bp 이상 확대되었다.' }],
    tip: '무위험자산(국채) 대비 위험자산의 추가 수익률로, 시장의 위험회피 심리를 보여주는 대표 지표입니다.',
    synonyms: [], antonyms: [], collocations: ['spread widening', 'credit spread tightening'] },
  { term: 'quantitative easing (QE)', ipa: '/kwɒnˈtɪt.ə.tɪv ˈiː.zɪŋ/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '양적완화',
    examples: [{ en: 'Years of quantitative easing kept borrowing costs artificially low, inflating asset valuations across the board.', ko: '수년간의 양적완화는 차입비용을 인위적으로 낮게 유지시켰고, 전반적인 자산가치 상승을 초래했다.' }],
    tip: '반대 개념은 quantitative tightening(양적긴축, QT). 중앙은행 통화정책 관련 리포트의 핵심 용어입니다.',
    synonyms: [], antonyms: ['quantitative tightening (QT)'], collocations: [] },
  { term: 'mark-to-market', ipa: '/mɑːrk tuː ˈmɑːr.kɪt/', pos: '명사구/형용사', type: 'phrase', category: 'realestate',
    meaningKo: '시가평가',
    examples: [{ en: 'Marking the loan book to market would reveal significant unrealized losses on the balance sheet.', ko: '대출 포트폴리오를 시가평가할 경우, 대차대조표상 상당한 미실현손실이 드러날 것이다.' }],
    tip: '장부가(book value)와 대비되는 개념으로, 금융위기 관련 리포트에서 은행·부동산 대출 부실 논의 시 자주 등장합니다.',
    synonyms: [], antonyms: ['book value'], collocations: ['mark-to-market loss'] },
  { term: 'counterparty risk', ipa: '/ˈkaʊn.tɚ.pɑːr.t̬i rɪsk/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '거래상대방 리스크',
    examples: [{ en: 'The swap agreement carries counterparty risk if the hedge provider were to default.', ko: '해당 스왑 계약은 헤지 제공기관이 부도날 경우 거래상대방 리스크를 수반한다.' }],
    tip: '파생상품 거래에서 계약 상대방이 의무를 이행하지 못할 위험을 뜻하며, 리스크관리 섹션에서 자주 언급됩니다.',
    synonyms: [], antonyms: [], collocations: ['counterparty exposure'] },
  { term: 'systemic risk', ipa: '/sɪˈstem.ɪk rɪsk/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '시스템 리스크(금융시스템 전반에 파급되는 위험)',
    examples: [{ en: 'Regulators are monitoring the private credit market for signs of systemic risk.', ko: '규제당국은 프라이빗 크레딧 시장에서 시스템 리스크의 징후를 모니터링하고 있다.' }],
    tip: '특정 기관이 아닌 금융시스템 전반에 전이될 수 있는 위험을 뜻하며, idiosyncratic risk(개별 리스크)와 대비됩니다.',
    synonyms: [], antonyms: ['idiosyncratic risk'], collocations: [] },
  { term: 'hedge', ipa: '/hedʒ/', pos: '동사/명사', type: 'word', category: 'realestate',
    meaningKo: '헤지하다; 헤지(위험회피 거래)',
    examples: [{ en: 'The borrower purchased an interest rate cap to hedge against further increases in floating-rate debt costs.', ko: '차주는 변동금리 대출비용의 추가 상승에 대비해 금리 캡을 매입해 헤지했다.' }],
    tip: '동사(위험을 회피하다)와 명사(헤지 수단) 모두로 쓰입니다. 부동산 대출에서는 interest rate cap/swap이 대표적인 헤지 수단입니다.',
    synonyms: ['offset risk'], antonyms: [], collocations: ['hedge against inflation', 'natural hedge'] },
  { term: 'illiquidity premium', ipa: '/ˌɪl.ɪˈkwɪd.ə.t̬i ˈpriː.mi.əm/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '유동성 프리미엄(비유동성 보상)',
    examples: [{ en: 'Private real estate is expected to offer an illiquidity premium relative to publicly traded equities.', ko: '사모 부동산은 상장 주식 대비 비유동성에 대한 보상, 즉 유동성 프리미엄을 제공할 것으로 기대된다.' }],
    tip: '즉시 현금화가 어려운 자산에 투자자가 요구하는 추가 수익률 개념으로, 부동산·사모펀드 투자논리에서 핵심적으로 쓰입니다.',
    synonyms: [], antonyms: ['liquidity premium'], collocations: [] },

  { term: 'asset-backed securities (ABS)', ipa: '/ˈæs.et bækt sɪˈkjʊr.ə.tiz/', pos: '명사구(약어 ABS)', type: 'phrase', category: 'realestate',
    meaningKo: '자산유동화증권',
    examples: [{ en: 'The fund also allocates a portion of its portfolio to asset-backed securities backed by auto loans.', ko: '그 펀드는 포트폴리오의 일부를 자동차 대출을 기초로 한 자산유동화증권에도 배분한다.' }],
    tip: 'CMBS(상업용 부동산저당증권)도 ABS의 한 종류로 볼 수 있습니다. 기초자산의 현금흐름을 담보로 발행되는 증권을 통칭합니다.',
    synonyms: [], antonyms: [], collocations: ['ABS issuance', 'backed by'] },
  { term: 'debt yield', ipa: '/det jiːld/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '부채수익률',
    examples: [{ en: 'Lenders increasingly underwrite to a minimum debt yield rather than relying solely on LTV.', ko: '대출기관들은 LTV에만 의존하기보다 최소 부채수익률 기준으로 대출을 심사하는 경우가 늘고 있다.' }],
    tip: 'debt yield = NOI ÷ 대출원금. LTV나 DSCR과 달리 자산가치 평가나 금리 변동의 영향을 받지 않는 보수적인 지표로 선호됩니다.',
    synonyms: [], antonyms: [], collocations: ['minimum debt yield'] },
  { term: 'rent roll', ipa: '/rent roʊl/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '임대차 현황표',
    examples: [{ en: 'The rent roll shows staggered lease expirations over the next five years.', ko: '임대차 현황표는 향후 5년간 임대차 계약 만료가 분산되어 있음을 보여준다.' }],
    tip: '실사(due diligence) 과정에서 반드시 검토하는 핵심 서류로, 임차인·임대료·계약기간이 정리되어 있습니다.',
    synonyms: [], antonyms: [], collocations: ['review the rent roll'] },
  { term: 'tenant improvement allowance (TI)', ipa: '/ˈten.ənt ɪmˈpruːv.mənt əˈlaʊ.əns/', pos: '명사구(약어 TI)', type: 'phrase', category: 'realestate',
    meaningKo: '임차인 인테리어 지원금',
    examples: [{ en: 'The landlord offered a $40-per-square-foot TI allowance to attract the tenant.', ko: '임대인은 임차인 유치를 위해 평방피트당 40달러의 인테리어 지원금을 제공했다.' }],
    tip: '신규 임차인 유치를 위한 인센티브 중 하나로, free rent(임대료 면제 기간)와 함께 자주 논의됩니다.',
    synonyms: [], antonyms: [], collocations: ['TI allowance', 'leasing incentive'] },
  { term: 'anchor tenant', ipa: '/ˈæŋ.kɚ ˈten.ənt/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '핵심 임차인 (쇼핑몰 등의 주력 점포)',
    examples: [{ en: "Losing the anchor tenant significantly weakened the shopping center's foot traffic.", ko: '핵심 임차인을 잃은 것은 쇼핑센터의 유동인구를 크게 약화시켰다.' }],
    tip: '리테일 부동산에서 다른 소규모 점포들의 집객력을 좌우하는 대형 임차인을 가리킵니다.',
    synonyms: [], antonyms: [], collocations: ['lose the anchor tenant'] },
  { term: 'absorption rate', ipa: '/əbˈzɔːrp.ʃən reɪt/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '공급 흡수율',
    examples: [{ en: 'The industrial market posted strong absorption despite record new supply.', ko: '산업용 부동산 시장은 기록적인 신규 공급에도 불구하고 강한 흡수율을 기록했다.' }],
    tip: '일정 기간 동안 시장에 신규 공급된 면적이 실제로 임대(흡수)되는 속도를 나타내며, vacancy rate와 함께 수급 상황을 보여줍니다.',
    synonyms: [], antonyms: [], collocations: ['net absorption', 'positive absorption'] },
  { term: 'gross leasable area (GLA)', ipa: '/ɡroʊs ˈliː.sə.bəl ˈer.i.ə/', pos: '명사구(약어 GLA)', type: 'phrase', category: 'realestate',
    meaningKo: '총 임대가능면적',
    examples: [{ en: "The mall's GLA totals 850,000 square feet across two levels.", ko: '그 몰의 총 임대가능면적은 2개 층에 걸쳐 총 85만 평방피트에 달한다.' }],
    tip: '리테일 자산에서 자주 쓰이는 면적 단위로, 공용면적을 제외한 실제 임대 가능한 면적을 의미합니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'carried interest', ipa: '/ˈker.id ˈɪn.trəst/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '성과보수 (캐리, GP가 초과수익에서 받는 몫)',
    examples: [{ en: 'The general partner earns a 20% carried interest above an 8% preferred return.', ko: 'GP(운용사)는 8% 우선수익률을 초과하는 부분에 대해 20%의 성과보수를 받는다.' }],
    tip: '사모펀드·부동산 펀드 구조에서 GP(운용사)의 핵심 수익원으로, preferred return(우선수익률)과 함께 이해해야 합니다.',
    synonyms: [], antonyms: [], collocations: ['earn carried interest'] },
  { term: 'syndication', ipa: '/ˌsɪn.dɪˈkeɪ.ʃən/', pos: '명사', type: 'word', category: 'realestate',
    meaningKo: '신디케이션(공동투자 구조)',
    examples: [{ en: 'The sponsor raised equity through a syndication of high-net-worth investors.', ko: '스폰서는 고액자산가 투자자들의 신디케이션을 통해 지분을 조달했다.' }],
    tip: '다수의 투자자를 모아 하나의 딜에 공동 투자하는 구조로, 대출 신디케이션(loan syndication)에도 동일하게 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['syndicate a deal'] },
  { term: 'balloon payment', ipa: '/bəˈluːn ˈpeɪ.mənt/', pos: '명사구', type: 'phrase', category: 'realestate',
    meaningKo: '만기일시상환금',
    examples: [{ en: 'The loan requires a large balloon payment at maturity, creating refinancing risk.', ko: '그 대출은 만기 시 큰 규모의 일시상환금을 요구해 재융자 리스크를 발생시킨다.' }],
    tip: '원리금 균등상환이 아니라 만기에 잔액을 한 번에 갚는 구조로, refinancing risk(재융자 리스크) 논의와 자주 함께 등장합니다.',
    synonyms: [], antonyms: [], collocations: ['balloon payment at maturity'] },

  // ---------------- 일상영어 ----------------
  { term: 'errand', ipa: '/ˈer.ənd/', pos: '명사', type: 'word', category: 'daily',
    meaningKo: '심부름, 볼일',
    examples: [{ en: "I have a few errands to run this afternoon.", ko: '오늘 오후에 볼일이 몇 가지 있어.' }],
    tip: '"run errands"가 세트 표현처럼 자주 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['run errands'] },
  { term: 'commute', ipa: '/kəˈmjuːt/', pos: '동사/명사', type: 'word', category: 'daily',
    meaningKo: '통근하다; 통근',
    examples: [{ en: 'My commute takes about 40 minutes each way.', ko: '내 통근시간은 편도 약 40분 걸린다.' }],
    tip: '"commuter"는 통근자를 뜻하는 명사입니다.',
    synonyms: [], antonyms: [], collocations: ['daily commute'] },
  { term: 'leftover', ipa: '/ˈleft.oʊ.vɚ/', pos: '명사/형용사', type: 'word', category: 'daily',
    meaningKo: '남은 음식',
    examples: [{ en: "I'll just heat up the leftovers for dinner.", ko: '저녁은 그냥 남은 음식 데워 먹을게.' }],
    tip: '보통 복수형 leftovers로 씁니다.',
    synonyms: [], antonyms: [], collocations: ['heat up leftovers'] },
  { term: 'procrastinate', ipa: '/proʊˈkræs.tə.neɪt/', pos: '동사', type: 'word', category: 'daily',
    meaningKo: '미루다, 꾸물거리다',
    examples: [{ en: 'I always procrastinate on paperwork.', ko: '나는 항상 서류 작업을 미룬다.' }],
    tip: '명사형은 procrastination.',
    synonyms: ['delay', 'put off'], antonyms: ['tackle immediately'], collocations: ['procrastinate on something'] },
  { term: 'under the weather', ipa: '/ˈʌn.dɚ ðə ˈweð.ɚ/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '몸이 좀 안 좋은',
    examples: [{ en: "I'm feeling a bit under the weather today.", ko: '오늘 몸이 좀 안 좋네.' }],
    tip: '심각한 병이 아니라 가벼운 컨디션 난조를 표현할 때 씁니다.',
    synonyms: ['feeling ill', 'not feeling well'], antonyms: [], collocations: [] },
  { term: 'grab a bite', ipa: '/ɡræb ə baɪt/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '간단히 먹다',
    examples: [{ en: 'Let’s grab a bite before the movie.', ko: '영화 보기 전에 간단히 뭐 좀 먹자.' }],
    tip: '캐주얼한 자리 제안에 자주 쓰이는 구어체 표현입니다.',
    synonyms: ['grab a snack'], antonyms: [], collocations: [] },
  { term: 'chores', ipa: '/tʃɔːrz/', pos: '명사', type: 'word', category: 'daily',
    meaningKo: '집안일',
    examples: [{ en: 'I spend Saturday mornings doing chores.', ko: '토요일 아침엔 집안일을 한다.' }],
    tip: '항상 복수형으로 씁니다.',
    synonyms: [], antonyms: [], collocations: ['do chores', 'household chores'] },
  { term: 'catch up', ipa: '/kætʃ ʌp/', pos: '구동사', type: 'phrase', category: 'daily',
    meaningKo: '밀린 이야기를 나누다, 근황을 나누다',
    examples: [{ en: 'We should catch up over coffee sometime.', ko: '언제 커피 마시면서 밀린 얘기 좀 하자.' }],
    tip: '업무 맥락에서도 "let\'s catch up next week"처럼 자주 쓰입니다.',
    synonyms: ['reconnect'], antonyms: [], collocations: ['catch up over coffee'] },
  { term: 'hang out', ipa: '/hæŋ aʊt/', pos: '구동사', type: 'phrase', category: 'daily',
    meaningKo: '놀다, 어울려 시간을 보내다',
    examples: [{ en: 'Do you want to hang out this weekend?', ko: '이번 주말에 같이 놀래?' }],
    tip: '격식 없는 사이에서 편하게 쓰는 표현입니다.',
    synonyms: ['spend time together'], antonyms: [], collocations: [] },
  { term: 'on the go', ipa: '/ɑːn ðə ɡoʊ/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '바쁘게 돌아다니는, 이동 중인',
    examples: [{ en: 'She’s always on the go between meetings.', ko: '그녀는 늘 회의들 사이를 바쁘게 오간다.' }],
    tip: '"grab food on the go"처럼 이동 중 무언가를 할 때도 씁니다.',
    synonyms: [], antonyms: [], collocations: ['grab food on the go'] },
  { term: 'call it a day', ipa: '/kɔːl ɪt ə deɪ/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '오늘은 여기까지 하다, 하루 일과를 마치다',
    examples: [{ en: "Let's call it a day and finish this tomorrow.", ko: '오늘은 여기까지 하고 내일 마무리하자.' }],
    tip: '업무를 마무리 지을 때 자연스럽게 쓸 수 있는 표현입니다.',
    synonyms: ['wrap up'], antonyms: [], collocations: [] },
  { term: 'spare time', ipa: '/sper taɪm/', pos: '명사구', type: 'phrase', category: 'daily',
    meaningKo: '여가 시간, 남는 시간',
    examples: [{ en: 'What do you do in your spare time?', ko: '여가 시간엔 뭐 하세요?' }],
    tip: '"free time"과 거의 동의어로 바꿔 쓸 수 있습니다.',
    synonyms: ['free time', 'leisure time'], antonyms: [], collocations: [] },
  { term: 'get the hang of', ipa: '/ɡet ðə hæŋ ʌv/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '요령을 터득하다, 익숙해지다',
    examples: [{ en: 'It took a while, but I finally got the hang of it.', ko: '시간이 좀 걸렸지만 결국 요령을 익혔다.' }],
    tip: '새로운 기술이나 업무에 적응했을 때 자연스럽게 쓸 수 있습니다.',
    synonyms: ['master', 'get used to'], antonyms: [], collocations: [] },
  { term: 'run late', ipa: '/rʌn leɪt/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '늦어지다, 지각하다',
    examples: [{ en: "Sorry, I'm running late — traffic is terrible.", ko: '미안, 좀 늦어. 차가 너무 막혀.' }],
    tip: '"be late"보다 진행 중인 지연 상황을 자연스럽게 표현합니다.',
    synonyms: [], antonyms: ['be on time', 'be punctual'], collocations: [] },

  { term: 'window shopping', ipa: '/ˈwɪn.doʊ ˈʃɑː.pɪŋ/', pos: '명사구', type: 'phrase', category: 'daily',
    meaningKo: '아이쇼핑 (사지 않고 구경만 하는 것)',
    examples: [{ en: 'We spent the afternoon window shopping downtown.', ko: '우리는 오후 내내 시내에서 아이쇼핑을 하며 보냈다.' }],
    tip: '한국어의 "아이쇼핑"은 콩글리시로, 영어로는 window shopping이 정확한 표현입니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'small talk', ipa: '/smɔːl tɔːk/', pos: '명사구', type: 'phrase', category: 'daily',
    meaningKo: '잡담, 가벼운 대화',
    examples: [{ en: "He's not a fan of small talk and prefers to get straight to the point.", ko: '그는 잡담을 별로 안 좋아해서 바로 본론으로 들어가는 걸 선호한다.' }],
    tip: '네트워킹이나 미팅 시작 전 어색함을 풀기 위한 가벼운 대화를 뜻합니다.',
    synonyms: [], antonyms: [], collocations: ['make small talk'] },
  { term: 'rain check', ipa: '/reɪn tʃek/', pos: '명사구', type: 'phrase', category: 'daily',
    meaningKo: '다음 기회로 미루기',
    examples: [{ en: 'Can I take a rain check on dinner tonight? Something came up.', ko: '오늘 저녁 식사는 다음으로 미뤄도 될까? 일이 좀 생겨서.' }],
    tip: '"take a rain check"라는 관용 표현으로, 원래 우천으로 취소된 경기의 교환권에서 유래했습니다.',
    synonyms: [], antonyms: [], collocations: ['take a rain check'] },
  { term: 'binge-watch', ipa: '/bɪndʒ wɑːtʃ/', pos: '동사', type: 'word', category: 'daily',
    meaningKo: '(드라마 등을) 몰아보다',
    examples: [{ en: 'I binge-watched the entire season over the weekend.', ko: '주말 동안 그 시즌 전체를 몰아봤다.' }],
    tip: '명사형은 binge-watching. 넷플릭스 등 스트리밍 시대에 자주 쓰이는 신조어성 표현입니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'treat yourself', ipa: '/triːt jɔːrˈself/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '스스로에게 선물하다, 호사를 누리다',
    examples: [{ en: "You've worked so hard this month — treat yourself to something nice.", ko: '이번 달 정말 열심히 했으니, 스스로에게 좋은 선물을 해봐.' }],
    tip: '"treat"는 동사로 "한턱내다"라는 의미도 있어 "I\'ll treat you"(내가 살게)로도 자주 쓰입니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'splurge', ipa: '/splɜːrdʒ/', pos: '동사/명사', type: 'word', category: 'daily',
    meaningKo: '돈을 펑펑 쓰다; 과소비',
    examples: [{ en: 'We splurged on a fancy hotel for our anniversary.', ko: '우리는 기념일을 위해 근사한 호텔에 돈을 펑펑 썼다.' }],
    tip: '"splurge on something" 형태로 흔히 쓰입니다.',
    synonyms: [], antonyms: ['scrimp', 'economize'], collocations: ['splurge on'] },
  { term: 'day off', ipa: '/deɪ ɔːf/', pos: '명사구', type: 'phrase', category: 'daily',
    meaningKo: '휴일, 쉬는 날',
    examples: [{ en: "I'm taking a day off next Friday to recharge.", ko: '다음 주 금요일에 재충전을 위해 하루 쉴 예정이다.' }],
    tip: '"take a day off"(하루 휴가를 내다) 형태로 자주 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['take a day off'] },
  { term: 'run out of', ipa: '/rʌn aʊt ʌv/', pos: '구동사', type: 'phrase', category: 'daily',
    meaningKo: '~이 떨어지다, 다 쓰다',
    examples: [{ en: 'We ran out of coffee, so I need to stop by the store.', ko: '커피가 다 떨어져서 가게에 들러야 해.' }],
    tip: '재고나 자원이 소진되는 상황에 폭넓게 쓰이는 매우 실용적인 구동사입니다.',
    synonyms: [], antonyms: [], collocations: ['run out of time'] },
  { term: 'make ends meet', ipa: '/meɪk endz miːt/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '겨우 먹고 살다, 수지를 맞추다',
    examples: [{ en: "With rent this high, it's hard to make ends meet.", ko: '임대료가 이렇게 높으니 겨우 먹고 살기도 힘들다.' }],
    tip: '수입과 지출의 균형을 겨우 맞춘다는 뉘앙스의 관용구입니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'creature of habit', ipa: '/ˈkriː.tʃɚ ʌv ˈhæb.ɪt/', pos: '관용구', type: 'phrase', category: 'daily',
    meaningKo: '습관의 동물 (늘 같은 패턴으로 사는 사람)',
    examples: [{ en: "I'm a creature of habit — I order the same thing every time.", ko: '난 습관의 동물이라 매번 같은 걸 주문해.' }],
    tip: '자신의 반복적인 습관을 가볍게 자조할 때 자주 쓰는 표현입니다.',
    synonyms: [], antonyms: [], collocations: [] },

  // ---------------- 비즈니스영어 ----------------
  { term: 'deadline', ipa: '/ˈded.laɪn/', pos: '명사', type: 'word', category: 'business',
    meaningKo: '마감기한',
    examples: [{ en: 'We need to meet the deadline for the Q3 report.', ko: '3분기 보고서 마감기한을 지켜야 한다.' }],
    tip: '"meet a deadline"(기한을 지키다), "miss a deadline"(기한을 놓치다)로 자주 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['meet a deadline', 'miss a deadline'] },
  { term: 'stakeholder', ipa: '/ˈsteɪk.hoʊl.dɚ/', pos: '명사', type: 'word', category: 'business',
    meaningKo: '이해관계자',
    examples: [{ en: 'We should get sign-off from all key stakeholders.', ko: '주요 이해관계자 전원의 승인을 받아야 한다.' }],
    tip: '주주(shareholder)보다 넓은 개념으로 고객, 직원, 협력사까지 포함합니다.',
    synonyms: [], antonyms: [], collocations: ['key stakeholders', 'stakeholder buy-in'] },
  { term: 'leverage', ipa: '/ˈlev.ər.ɪdʒ/', pos: '동사/명사', type: 'word', category: 'business',
    meaningKo: '활용하다; 지렛대 효과, 레버리지',
    examples: [{ en: 'We can leverage our existing network to enter the new market.', ko: '기존 네트워크를 활용해 새 시장에 진입할 수 있다.' }],
    tip: '재무에서는 "차입 비율", 일반 비즈니스에서는 "적극 활용하다"라는 동사로도 흔히 씁니다.',
    synonyms: ['utilize', 'capitalize on'], antonyms: [], collocations: ['leverage a network'] },
  { term: 'synergy', ipa: '/ˈsɪn.ɚ.dʒi/', pos: '명사', type: 'word', category: 'business',
    meaningKo: '시너지, 상승효과',
    examples: [{ en: 'The merger is expected to create significant synergies.', ko: '이번 합병으로 상당한 시너지가 발생할 것으로 예상된다.' }],
    tip: '형용사형은 synergistic.',
    synonyms: ['synergies'], antonyms: [], collocations: ['create synergy'] },
  { term: 'circle back', ipa: '/ˈsɝː.kəl bæk/', pos: '관용구', type: 'phrase', category: 'business',
    meaningKo: '나중에 다시 논의하다',
    examples: [{ en: "Let's circle back on this after we get more data.", ko: '데이터가 좀 더 모이면 이 건은 다시 논의하자.' }],
    tip: '회의에서 결론을 미룰 때 자주 쓰는 정중한 표현입니다.',
    synonyms: ['revisit', 'follow up later'], antonyms: [], collocations: [] },
  { term: 'streamline', ipa: '/ˈstriːm.laɪn/', pos: '동사', type: 'word', category: 'business',
    meaningKo: '간소화하다, 효율화하다',
    examples: [{ en: 'We streamlined the approval process to save time.', ko: '시간을 절약하기 위해 승인 절차를 간소화했다.' }],
    tip: '프로세스, 워크플로우를 효율적으로 만들 때 흔히 사용됩니다.',
    synonyms: ['simplify', 'optimize'], antonyms: ['complicate'], collocations: ['streamline a process'] },
  { term: 'bottom line', ipa: '/ˈbɑːt̬.əm laɪn/', pos: '관용구', type: 'phrase', category: 'business',
    meaningKo: '핵심, 최종 결과 (순이익)',
    examples: [{ en: 'The bottom line is we need more budget for this project.', ko: '핵심은 이 프로젝트에 예산이 더 필요하다는 것이다.' }],
    tip: '원래 손익계산서 맨 아랫줄(순이익)에서 유래한 표현입니다.',
    synonyms: ['net profit', 'key takeaway'], antonyms: [], collocations: [] },
  { term: 'ballpark figure', ipa: '/ˈbɔːl.pɑːrk ˈfɪɡ.jɚ/', pos: '명사구', type: 'phrase', category: 'business',
    meaningKo: '대략적인 수치, 어림값',
    examples: [{ en: 'Can you give me a ballpark figure for the total cost?', ko: '총비용 대략적인 수치 좀 알려줄 수 있어?' }],
    tip: '정확한 숫자가 아직 없을 때 캐주얼하게 요청할 수 있는 표현입니다.',
    synonyms: ['rough estimate'], antonyms: ['exact figure'], collocations: [] },
  { term: 'on the same page', ipa: '/ɑːn ðə seɪm peɪdʒ/', pos: '관용구', type: 'phrase', category: 'business',
    meaningKo: '의견이 일치하는, 같은 이해를 공유하는',
    examples: [{ en: "Let's make sure we're all on the same page before the client call.", ko: '고객 통화 전에 우리 모두 같은 이해를 공유하고 있는지 확인하자.' }],
    tip: '회의 시작 전 정렬(align) 상태를 확인할 때 매우 자주 쓰입니다.',
    synonyms: [], antonyms: ['at odds', 'out of sync'], collocations: [] },
  { term: 'proactive', ipa: '/proʊˈæk.tɪv/', pos: '형용사', type: 'word', category: 'business',
    meaningKo: '주도적인, 사전 대응하는',
    examples: [{ en: 'She took a proactive approach to resolving the issue.', ko: '그녀는 그 문제를 해결하는 데 주도적인 접근을 취했다.' }],
    tip: '반대말은 reactive(대응적인, 사후 대처하는).',
    synonyms: [], antonyms: ['reactive'], collocations: ['proactive approach'] },
  { term: 'onboard', ipa: '/ˈɑːn.bɔːrd/', pos: '동사', type: 'word', category: 'business',
    meaningKo: '합류시키다, (신입을) 적응시키다',
    examples: [{ en: 'We onboarded three new hires this week.', ko: '이번 주에 신입사원 세 명을 온보딩했다.' }],
    tip: '명사형 onboarding은 신입 적응 프로그램 자체를 지칭합니다.',
    synonyms: ['integrate'], antonyms: ['offboard'], collocations: ['onboard a new hire'] },
  { term: 'bandwidth', ipa: '/ˈbænd.wɪtθ/', pos: '명사', type: 'word', category: 'business',
    meaningKo: '(업무를 처리할) 여력, 시간적 여유',
    examples: [{ en: "I don't have the bandwidth to take on another project right now.", ko: '지금은 다른 프로젝트를 맡을 여력이 없어.' }],
    tip: '원래 통신 대역폭이지만 비즈니스에서 "일할 여력"의 비유로 매우 흔하게 씁니다.',
    synonyms: ['capacity'], antonyms: [], collocations: ['have the bandwidth'] },
  { term: 'actionable', ipa: '/ˈæk.ʃən.ə.bəl/', pos: '형용사', type: 'word', category: 'business',
    meaningKo: '실행 가능한, 바로 조치할 수 있는',
    examples: [{ en: 'We need actionable insights, not just raw data.', ko: '단순 데이터가 아니라 실행 가능한 인사이트가 필요하다.' }],
    tip: '보고서나 분석 결과를 평가할 때 자주 등장하는 형용사입니다.',
    synonyms: [], antonyms: [], collocations: ['actionable insight'] },
  { term: 'follow up', ipa: '/ˈfɑː.loʊ ʌp/', pos: '구동사', type: 'phrase', category: 'business',
    meaningKo: '후속 조치를 하다, 뒤이어 연락하다',
    examples: [{ en: "I'll follow up with the client by email tomorrow.", ko: '내일 이메일로 고객에게 후속 연락을 할게.' }],
    tip: '명사로 쓸 때는 "follow-up"(하이픈 포함)으로 표기하는 경우가 많습니다.',
    synonyms: ['check in'], antonyms: [], collocations: ['follow-up email'] },
  { term: 'put on hold', ipa: '/pʊt ɑːn hoʊld/', pos: '관용구', type: 'phrase', category: 'business',
    meaningKo: '보류하다',
    examples: [{ en: 'The project has been put on hold due to budget cuts.', ko: '예산 삭감으로 그 프로젝트는 보류되었다.' }],
    tip: '전화 통화에서 "hold on"(잠시 기다리다)과 헷갈리지 않도록 주의하세요.',
    synonyms: ['postpone', 'pause'], antonyms: ['proceed with'], collocations: [] },

  { term: 'touch base', ipa: '/tʌtʃ beɪs/', pos: '관용구', type: 'phrase', category: 'business',
    meaningKo: '(짧게) 연락하다, 의견을 나누다',
    examples: [{ en: "Let's touch base early next week to review progress.", ko: '다음 주 초에 짧게 연락해서 진행 상황을 점검하자.' }],
    tip: 'circle back(나중에 다시 논의하다)과 짝을 이루는 표현으로, touch base는 캐주얼한 확인·소통에 가깝습니다.',
    synonyms: [], antonyms: [], collocations: ['touch base with'] },
  { term: 'low-hanging fruit', ipa: '/loʊ ˈhæŋ.ɪŋ fruːt/', pos: '관용구', type: 'phrase', category: 'business',
    meaningKo: '쉽게 얻을 수 있는 성과',
    examples: [{ en: "Let's tackle the low-hanging fruit first before moving to bigger initiatives.", ko: '더 큰 과제로 넘어가기 전에 쉽게 얻을 수 있는 성과부터 처리하자.' }],
    tip: '적은 노력으로 빠르게 달성 가능한 목표를 비유적으로 표현합니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'move the needle', ipa: '/muːv ðə ˈniː.dəl/', pos: '관용구', type: 'phrase', category: 'business',
    meaningKo: '유의미한 변화를 만들다',
    examples: [{ en: "This campaign didn't really move the needle on sales.", ko: '이 캠페인은 매출에 별다른 유의미한 변화를 만들지 못했다.' }],
    tip: '계기판 바늘이 움직이는 이미지에서 유래한 표현으로, 측정 가능한 실질적 영향을 뜻합니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'game plan', ipa: '/ɡeɪm plæn/', pos: '명사구', type: 'phrase', category: 'business',
    meaningKo: '전략, 계획',
    examples: [{ en: "What's our game plan for the client presentation tomorrow?", ko: '내일 고객 발표를 위한 우리 전략이 뭐지?' }],
    tip: '스포츠에서 유래했지만 비즈니스에서 "구체적인 실행 전략"을 뜻하는 캐주얼한 표현으로 자주 쓰입니다.',
    synonyms: ['strategy'], antonyms: [], collocations: ['have a game plan'] },
  { term: 'drill down', ipa: '/drɪl daʊn/', pos: '구동사', type: 'phrase', category: 'business',
    meaningKo: '세부적으로 파고들다',
    examples: [{ en: "Let's drill down into the regional numbers to see what's driving the decline.", ko: '하락의 원인을 파악하기 위해 지역별 수치를 세부적으로 파고들어 보자.' }],
    tip: '"drill down into + 대상" 형태로 자주 쓰이며, 데이터 분석 맥락에서 특히 흔합니다.',
    synonyms: [], antonyms: [], collocations: ['drill down into'] },
  { term: 'red tape', ipa: '/red teɪp/', pos: '명사구', type: 'phrase', category: 'business',
    meaningKo: '관료적 형식주의, 번거로운 절차',
    examples: [{ en: 'Cutting through the red tape took months longer than expected.', ko: '그 번거로운 행정 절차를 뚫는 데 예상보다 몇 달이 더 걸렸다.' }],
    tip: '과도한 규정·서류 절차를 부정적으로 묘사할 때 쓰는 표현입니다.',
    synonyms: ['bureaucracy'], antonyms: [], collocations: ['cut through red tape'] },
  { term: 'win-win', ipa: '/wɪn wɪn/', pos: '형용사', type: 'word', category: 'business',
    meaningKo: '상호 이익이 되는',
    examples: [{ en: 'The partnership turned out to be a win-win for both companies.', ko: '그 파트너십은 양사 모두에게 상호 이익이 되는 것으로 판명되었다.' }],
    tip: '반대는 zero-sum(제로섬, 한쪽이 얻으면 한쪽이 잃는 구조)입니다.',
    synonyms: [], antonyms: ['zero-sum'], collocations: ['win-win situation'] },
  { term: 'deep dive', ipa: '/diːp daɪv/', pos: '명사구', type: 'phrase', category: 'business',
    meaningKo: '심층 분석',
    examples: [{ en: 'We scheduled a deep dive into the Q3 numbers next week.', ko: '다음 주에 3분기 수치에 대한 심층 분석 시간을 잡았다.' }],
    tip: '명사와 동사(deep-dive into)로 모두 쓰이며, drill down과 비슷한 뉘앙스입니다.',
    synonyms: [], antonyms: [], collocations: ['do a deep dive'] },
  { term: 'buy-in', ipa: '/baɪ ɪn/', pos: '명사', type: 'word', category: 'business',
    meaningKo: '동의, 지지',
    examples: [{ en: 'We need executive buy-in before rolling this out company-wide.', ko: '전사적으로 시행하기 전에 경영진의 동의가 필요하다.' }],
    tip: '"get buy-in from"(~로부터 동의를 얻다) 형태로 자주 쓰입니다.',
    synonyms: ['support', 'endorsement'], antonyms: [], collocations: ['get buy-in'] },
  { term: 'rubber stamp', ipa: '/ˈrʌb.ɚ stæmp/', pos: '동사/명사', type: 'word', category: 'business',
    meaningKo: '(형식적으로) 승인하다; 형식적 승인',
    examples: [{ en: "The board simply rubber-stamped the CEO's decision.", ko: '이사회는 CEO의 결정을 그냥 형식적으로 승인했다.' }],
    tip: '실질적인 검토 없이 습관적으로 승인한다는 부정적 뉘앙스를 담고 있습니다.',
    synonyms: [], antonyms: [], collocations: [] },

  // ---------------- 심화영어 (고급 어휘) ----------------
  { term: 'ubiquitous', ipa: '/juːˈbɪk.wə.t̬əs/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '어디에나 있는, 편재하는',
    examples: [{ en: 'Smartphones have become ubiquitous in modern business.', ko: '스마트폰은 현대 비즈니스에서 어디에나 존재하게 되었다.' }],
    tip: '격식 있는 글이나 보고서에서 "everywhere"보다 세련되게 쓰입니다.',
    synonyms: ['omnipresent', 'pervasive'], antonyms: ['rare'], collocations: [] },
  { term: 'mitigate', ipa: '/ˈmɪt̬.ə.ɡeɪt/', pos: '동사', type: 'word', category: 'advanced',
    meaningKo: '완화하다, 경감시키다',
    examples: [{ en: 'We implemented new controls to mitigate the risk.', ko: '리스크를 완화하기 위해 새로운 통제 장치를 도입했다.' }],
    tip: '리스크·손실·영향을 줄인다는 맥락에서 리포트에 매우 자주 등장합니다.',
    synonyms: ['alleviate', 'reduce'], antonyms: ['exacerbate'], collocations: ['mitigate risk'] },
  { term: 'paradigm', ipa: '/ˈper.ə.daɪm/', pos: '명사', type: 'word', category: 'advanced',
    meaningKo: '패러다임, 사고의 틀',
    examples: [{ en: 'The industry is undergoing a paradigm shift toward remote work.', ko: '그 업계는 원격근무로의 패러다임 전환을 겪고 있다.' }],
    tip: '"paradigm shift"(패러다임 전환)가 세트 표현으로 매우 흔히 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['paradigm shift'] },
  { term: 'discrepancy', ipa: '/dɪˈskrep.ən.si/', pos: '명사', type: 'word', category: 'advanced',
    meaningKo: '불일치, 차이',
    examples: [{ en: 'There is a discrepancy between the two valuation reports.', ko: '두 감정평가 보고서 사이에 불일치가 있다.' }],
    tip: '수치나 기록 간의 차이를 지적할 때 격식 있게 쓰이는 표현입니다.',
    synonyms: ['inconsistency'], antonyms: ['consistency'], collocations: [] },
  { term: 'exacerbate', ipa: '/ɪɡˈzæs.ɚ.beɪt/', pos: '동사', type: 'word', category: 'advanced',
    meaningKo: '악화시키다',
    examples: [{ en: 'Rising interest rates could exacerbate the housing slowdown.', ko: '금리 인상이 주택시장 둔화를 악화시킬 수 있다.' }],
    tip: '"worsen"보다 격식 있는 표현으로, 경제/시장 분석 글에서 자주 보입니다.',
    synonyms: ['worsen', 'aggravate'], antonyms: ['mitigate', 'alleviate'], collocations: [] },
  { term: 'arbitrary', ipa: '/ˈɑːr.bə.trer.i/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '임의적인, 자의적인',
    examples: [{ en: 'The decision seemed arbitrary and lacked clear justification.', ko: '그 결정은 임의적으로 보였고 명확한 근거가 부족했다.' }],
    tip: '기준 없이 임의로 정해졌다는 부정적 뉘앙스를 담고 있습니다.',
    synonyms: ['random', 'capricious'], antonyms: ['reasoned', 'justified'], collocations: [] },
  { term: 'pragmatic', ipa: '/præɡˈmæt̬.ɪk/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '실용적인, 실리적인',
    examples: [{ en: 'We took a pragmatic approach given the tight timeline.', ko: '빠듯한 일정을 감안해 실용적인 접근을 취했다.' }],
    tip: '이상론(idealistic)과 대비되는 개념으로 자주 사용됩니다.',
    synonyms: ['practical'], antonyms: ['idealistic'], collocations: [] },
  { term: 'conducive', ipa: '/kənˈduː.sɪv/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '~에 도움이 되는, 좋은 여건을 만드는',
    examples: [{ en: 'Low interest rates are conducive to real estate investment.', ko: '저금리는 부동산 투자에 우호적인 여건을 만든다.' }],
    tip: '항상 "conducive to + 명사/동명사" 형태로 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['conducive to growth'] },
  { term: 'nuance', ipa: '/ˈnuː.ɑːns/', pos: '명사', type: 'word', category: 'advanced',
    meaningKo: '미묘한 차이, 뉘앙스',
    examples: [{ en: 'It takes experience to understand the nuances of contract negotiation.', ko: '계약 협상의 미묘한 뉘앙스를 이해하려면 경험이 필요하다.' }],
    tip: '형용사형 nuanced("미묘한 차이를 반영한")도 자주 쓰입니다.',
    synonyms: ['subtlety'], antonyms: [], collocations: [] },
  { term: 'cognizant', ipa: '/ˈkɑːɡ.nə.zənt/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '인식하고 있는, 알고 있는',
    examples: [{ en: 'We are cognizant of the risks involved in this transaction.', ko: '우리는 이 거래에 수반되는 리스크를 인지하고 있다.' }],
    tip: '"aware of"의 격식 있는 대체 표현으로 공식 문서에서 자주 쓰입니다.',
    synonyms: ['aware'], antonyms: ['oblivious'], collocations: ['cognizant of'] },
  { term: 'delineate', ipa: '/dɪˈlɪn.i.eɪt/', pos: '동사', type: 'word', category: 'advanced',
    meaningKo: '명확히 기술하다, (경계를) 규정하다',
    examples: [{ en: 'The contract clearly delineates each party’s responsibilities.', ko: '그 계약서는 각 당사자의 책임을 명확히 규정하고 있다.' }],
    tip: '법률/계약 문서에서 범위나 책임을 명시할 때 자주 등장합니다.',
    synonyms: ['define', 'outline'], antonyms: [], collocations: [] },
  { term: 'corroborate', ipa: '/kəˈrɑːb.ə.reɪt/', pos: '동사', type: 'word', category: 'advanced',
    meaningKo: '뒷받침하다, 확증하다',
    examples: [{ en: 'The additional data corroborates our initial findings.', ko: '추가 데이터가 우리의 초기 조사 결과를 뒷받침한다.' }],
    tip: '증거나 자료가 기존 주장을 강화할 때 리포트에서 자주 씁니다.',
    synonyms: ['confirm', 'substantiate'], antonyms: ['refute', 'contradict'], collocations: [] },
  { term: 'juxtapose', ipa: '/ˈdʒʌk.stə.poʊz/', pos: '동사', type: 'word', category: 'advanced',
    meaningKo: '나란히 놓다, 대조시키다',
    examples: [{ en: 'The report juxtaposes last year’s figures with this year’s projections.', ko: '그 보고서는 작년 수치와 올해 전망치를 나란히 대조한다.' }],
    tip: '명사형은 juxtaposition.',
    synonyms: ['contrast'], antonyms: [], collocations: [] },
  { term: 'a double-edged sword', ipa: '/ə ˈdʌb.əl edʒd sɔːrd/', pos: '관용구', type: 'phrase', category: 'advanced',
    meaningKo: '양날의 검 (장단점이 공존하는 것)',
    examples: [{ en: 'Leverage can be a double-edged sword — it amplifies both gains and losses.', ko: '레버리지는 양날의 검이 될 수 있다. 이익과 손실을 모두 증폭시키기 때문이다.' }],
    tip: '장점과 단점을 동시에 가진 사안을 묘사할 때 유용한 격식 있는 관용구입니다.',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'read between the lines', ipa: '/riːd bɪˈtwiːn ðə laɪnz/', pos: '관용구', type: 'phrase', category: 'advanced',
    meaningKo: '행간을 읽다, 숨은 의미를 파악하다',
    examples: [{ en: 'If you read between the lines, the client is clearly unhappy with the price.', ko: '행간을 읽어보면, 고객은 분명 가격에 불만족스러워하고 있다.' }],
    tip: '직접 언급되지 않은 진짜 의도를 파악한다는 뉘앙스입니다.',
    synonyms: [], antonyms: [], collocations: [] },

  { term: 'meticulous', ipa: '/məˈtɪk.jə.ləs/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '꼼꼼한, 세심한',
    examples: [{ en: 'The report reflects meticulous attention to detail.', ko: '그 보고서는 세부사항에 대한 꼼꼼한 주의를 반영하고 있다.' }],
    tip: '"meticulous"는 긍정적 뉘앙스로 꼼꼼함을 칭찬할 때 쓰입니다.',
    synonyms: ['thorough', 'painstaking'], antonyms: ['careless', 'sloppy'], collocations: ['meticulous attention to detail'] },
  { term: 'resilient', ipa: '/rɪˈzɪl.jənt/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '회복력 있는, 탄력적인',
    examples: [{ en: 'The local economy proved resilient despite the downturn.', ko: '지역 경제는 경기 침체에도 불구하고 회복력을 보였다.' }],
    tip: '명사형은 resilience. 리스크·위기 대응 능력을 논할 때 자주 등장합니다.',
    synonyms: ['tough', 'adaptable'], antonyms: ['fragile', 'vulnerable'], collocations: ['prove resilient'] },
  { term: 'tangible', ipa: '/ˈtæn.dʒə.bəl/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '유형의, 명백한',
    examples: [{ en: 'We need tangible evidence before making this investment.', ko: '이 투자를 하기 전에 명백한 증거가 필요하다.' }],
    tip: '반대는 intangible(무형의). 회계에서 유형자산/무형자산 구분에도 그대로 쓰입니다.',
    synonyms: ['concrete', 'palpable'], antonyms: ['intangible', 'abstract'], collocations: ['tangible evidence'] },
  { term: 'innate', ipa: '/ɪˈneɪt/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '타고난, 선천적인',
    examples: [{ en: 'She has an innate ability to read the room.', ko: '그녀는 분위기를 파악하는 타고난 능력이 있다.' }],
    tip: 'acquired(후천적으로 습득한)와 대비되는 개념입니다.',
    synonyms: ['inherent', 'inborn'], antonyms: ['acquired', 'learned'], collocations: [] },
  { term: 'discern', ipa: '/dɪˈsɝːn/', pos: '동사', type: 'word', category: 'advanced',
    meaningKo: '식별하다, 분별하다',
    examples: [{ en: 'It can be difficult to discern genuine demand from speculative interest.', ko: '실수요와 투기적 관심을 분별하기는 어려울 수 있다.' }],
    tip: '형용사형 discerning은 "안목 있는"이라는 뜻으로도 쓰입니다.',
    synonyms: ['distinguish', 'perceive'], antonyms: [], collocations: ['discern between'] },
  { term: 'compelling', ipa: '/kəmˈpel.ɪŋ/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '설득력 있는, 강력한',
    examples: [{ en: 'The data presents a compelling case for expansion.', ko: '그 데이터는 확장에 대한 설득력 있는 근거를 제시한다.' }],
    tip: '"compelling case/argument/evidence" 형태로 매우 자주 쓰입니다.',
    synonyms: ['persuasive', 'convincing'], antonyms: ['unconvincing'], collocations: ['compelling case'] },
  { term: 'formidable', ipa: '/ˈfɔːr.mə.də.bəl/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '만만치 않은, 강력한',
    examples: [{ en: 'The company faces a formidable competitor in this market.', ko: '그 회사는 이 시장에서 만만치 않은 경쟁자를 마주하고 있다.' }],
    tip: '위협적일 정도로 강하다는 뉘앙스로, 상대방을 존중하며 경계할 때 씁니다.',
    synonyms: ['daunting', 'redoubtable'], antonyms: ['weak', 'negligible'], collocations: ['formidable competitor'] },
  { term: 'deft', ipa: '/deft/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '능숙한, 솜씨 좋은',
    examples: [{ en: 'Her deft handling of the negotiation impressed everyone.', ko: '그녀의 능숙한 협상 처리는 모두에게 깊은 인상을 남겼다.' }],
    tip: '부사형 deftly로도 자주 쓰입니다 (예: "deftly navigated the crisis").',
    synonyms: ['skillful', 'adept'], antonyms: ['clumsy', 'inept'], collocations: [] },
  { term: 'tenuous', ipa: '/ˈten.ju.əs/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '근거가 빈약한, 미약한',
    examples: [{ en: 'The connection between the two events is tenuous at best.', ko: '그 두 사건 사이의 연관성은 기껏해야 미약한 수준이다.' }],
    tip: '논리나 관계가 약하다는 부정적 뉘앙스로, 격식 있는 비판에 자주 쓰입니다.',
    synonyms: ['weak', 'flimsy'], antonyms: ['solid', 'robust'], collocations: ['tenuous connection'] },
  { term: 'austere', ipa: '/ɔːˈstɪr/', pos: '형용사', type: 'word', category: 'advanced',
    meaningKo: '검소한, 엄격한, 긴축적인',
    examples: [{ en: 'The government introduced austere fiscal measures to curb the deficit.', ko: '정부는 재정적자를 줄이기 위해 긴축적인 재정 조치를 도입했다.' }],
    tip: '명사형 austerity(긴축)는 거시경제 뉴스에서 매우 자주 등장합니다.',
    synonyms: ['stark', 'severe'], antonyms: ['lavish', 'extravagant'], collocations: ['austerity measures'] },

  // ---------------- 토익 (TOEIC) ----------------
  { term: 'reimbursement', ipa: '/ˌriː.ɪmˈbɝːs.mənt/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '환급, 상환',
    examples: [{ en: 'Employees can submit receipts for travel reimbursement within 30 days.', ko: '직원들은 30일 이내에 출장비 환급을 위해 영수증을 제출할 수 있다.' }],
    tip: '동사형은 reimburse (reimburse A for B: A에게 B를 환급하다).',
    synonyms: ['repayment'], antonyms: [], collocations: ['submit for reimbursement', 'reimbursement request'] },
  { term: 'invoice', ipa: '/ˈɪn.vɔɪs/', pos: '명사/동사', type: 'word', category: 'toeic',
    meaningKo: '송장, 청구서; 청구서를 보내다',
    examples: [{ en: 'Please send the invoice to the accounting department by Friday.', ko: '금요일까지 회계부서로 청구서를 보내주세요.' }],
    tip: 'receipt(영수증, 결제 완료 증빙)와 달리 invoice는 대금 청구를 위한 문서입니다.',
    synonyms: ['bill'], antonyms: [], collocations: ['issue an invoice', 'outstanding invoice'] },
  { term: 'itinerary', ipa: '/aɪˈtɪn.ə.rer.i/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '여행 일정(표)',
    examples: [{ en: 'The travel agency emailed us a detailed itinerary for the conference trip.', ko: '여행사가 우리에게 컨퍼런스 출장을 위한 상세 일정표를 이메일로 보냈다.' }],
    tip: 'schedule(일반 일정)보다 여행/출장 경로 중심의 일정표를 가리킵니다.',
    synonyms: [], antonyms: [], collocations: ['detailed itinerary', 'travel itinerary'] },
  { term: 'warranty', ipa: '/ˈwɔːr.ən.ti/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '품질보증(서)',
    examples: [{ en: 'The printer comes with a two-year warranty.', ko: '그 프린터는 2년 품질보증이 함께 제공된다.' }],
    tip: '동사형 warrant(보증하다, 정당화하다)와 헷갈리지 않도록 주의하세요.',
    synonyms: [], antonyms: [], collocations: ['under warranty', 'warranty period'] },
  { term: 'complimentary', ipa: '/ˌkɑːm.pləˈmen.tər.i/', pos: '형용사', type: 'word', category: 'toeic',
    meaningKo: '무료의, 서비스로 제공되는',
    examples: [{ en: 'Complimentary breakfast is included in the room rate.', ko: '무료 조식이 객실 요금에 포함되어 있다.' }],
    tip: '"free"보다 격식 있는 표현으로, 호텔/항공 등 서비스업 지문에 자주 등장합니다.',
    synonyms: ['free of charge'], antonyms: [], collocations: ['complimentary breakfast', 'complimentary shuttle'] },
  { term: 'inventory', ipa: '/ˈɪn.vən.tɔːr.i/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '재고(품)',
    examples: [{ en: 'The warehouse conducts an inventory check at the end of every month.', ko: '그 창고는 매달 말 재고 조사를 실시한다.' }],
    tip: '"take/conduct inventory" 형태로 자주 씁니다.',
    synonyms: [], antonyms: [], collocations: ['inventory check', 'excess inventory'] },
  { term: 'shipment', ipa: '/ˈʃɪp.mənt/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '배송(물), 선적',
    examples: [{ en: 'The shipment was delayed due to a customs inspection.', ko: '그 배송은 세관 검사로 인해 지연되었다.' }],
    tip: '',
    synonyms: ['delivery'], antonyms: [], collocations: ['track a shipment', 'delayed shipment'] },
  { term: 'quotation', ipa: '/kwoʊˈteɪ.ʃən/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '견적(서)',
    examples: [{ en: 'We received three quotations before selecting a supplier.', ko: '우리는 공급업체를 선정하기 전에 세 건의 견적서를 받았다.' }],
    tip: '실무에서는 줄여서 "quote"라고도 자주 부릅니다.',
    synonyms: ['quote', 'estimate'], antonyms: [], collocations: ['request a quotation'] },
  { term: 'premises', ipa: '/ˈprem.ɪs.ɪz/', pos: '명사(복수)', type: 'word', category: 'toeic',
    meaningKo: '구내, 부지, 건물',
    examples: [{ en: 'Smoking is not permitted anywhere on the premises.', ko: '구내 어디에서도 흡연이 허용되지 않는다.' }],
    tip: '항상 복수형으로 쓰이며 단수 premise는 "전제"라는 전혀 다른 뜻입니다.',
    synonyms: [], antonyms: [], collocations: ['on the premises', 'company premises'] },
  { term: 'voucher', ipa: '/ˈvaʊ.tʃɚ/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '상품권, 쿠폰, 바우처',
    examples: [{ en: 'Customers who complete the survey will receive a discount voucher.', ko: '설문을 완료한 고객은 할인 바우처를 받게 된다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: ['gift voucher', 'redeem a voucher'] },
  { term: 'subsidiary', ipa: '/səbˈsɪd.i.er.i/', pos: '명사/형용사', type: 'word', category: 'toeic',
    meaningKo: '자회사; 부수적인',
    examples: [{ en: 'The company operates through several subsidiaries across Asia.', ko: '그 회사는 아시아 전역의 여러 자회사를 통해 운영된다.' }],
    tip: '모회사는 parent company. 대비 개념으로 함께 익혀두면 좋습니다.',
    synonyms: [], antonyms: ['parent company'], collocations: ['wholly owned subsidiary'] },
  { term: 'renovate', ipa: '/ˈren.ə.veɪt/', pos: '동사', type: 'word', category: 'toeic',
    meaningKo: '개조하다, 보수하다',
    examples: [{ en: 'The lobby will be renovated next month.', ko: '로비는 다음 달에 개조될 예정이다.' }],
    tip: '',
    synonyms: ['refurbish', 'remodel'], antonyms: [], collocations: ['renovate a building'] },
  { term: 'endorse', ipa: '/ɪnˈdɔːrs/', pos: '동사', type: 'word', category: 'toeic',
    meaningKo: '(공개적으로) 지지하다, 보증하다, (수표에) 배서하다',
    examples: [{ en: 'The CEO publicly endorsed the new marketing strategy.', ko: 'CEO는 새로운 마케팅 전략을 공개적으로 지지했다.' }],
    tip: '제품 광고 맥락에서는 유명인의 "보증 광고(endorsement)"를 의미하기도 합니다.',
    synonyms: ['support', 'back'], antonyms: [], collocations: ['endorse a proposal'] },
  { term: 'prerequisite', ipa: '/ˌpriːˈrek.wə.zɪt/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '전제 조건, 필요조건',
    examples: [{ en: 'Completing the training course is a prerequisite for promotion.', ko: '교육과정을 이수하는 것이 승진의 전제 조건이다.' }],
    tip: '',
    synonyms: ['requirement', 'precondition'], antonyms: [], collocations: ['prerequisite for'] },
  { term: 'correspondence', ipa: '/ˌkɔːr.əˈspɑːn.dəns/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '서신(왕래), 연락',
    examples: [{ en: 'All correspondence with clients should be documented.', ko: '고객과의 모든 서신은 기록되어야 한다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: ['business correspondence'] },
  { term: 'punctual', ipa: '/ˈpʌŋk.tʃu.əl/', pos: '형용사', type: 'word', category: 'toeic',
    meaningKo: '시간을 잘 지키는',
    examples: [{ en: 'Employees are expected to be punctual for all meetings.', ko: '직원들은 모든 회의에 시간을 잘 지킬 것으로 기대된다.' }],
    tip: '',
    synonyms: [], antonyms: ['late', 'tardy'], collocations: ['punctual arrival'] },
  { term: 'redeem', ipa: '/rɪˈdiːm/', pos: '동사', type: 'word', category: 'toeic',
    meaningKo: '(쿠폰/포인트 등을) 교환하다, 상환하다',
    examples: [{ en: 'You can redeem your points for a free hotel stay.', ko: '포인트로 무료 숙박을 교환받을 수 있다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: ['redeem a voucher', 'redeem points'] },
  { term: 'stipulate', ipa: '/ˈstɪp.jə.leɪt/', pos: '동사', type: 'word', category: 'toeic',
    meaningKo: '(계약 등에서) 규정하다, 명시하다',
    examples: [{ en: 'The contract stipulates that payment must be made within 15 days.', ko: '계약서는 대금이 15일 이내에 지급되어야 한다고 규정한다.' }],
    tip: '',
    synonyms: ['specify', 'mandate'], antonyms: [], collocations: ['the contract stipulates'] },
  { term: 'on behalf of', ipa: '/ɑːn bɪˈhæf ʌv/', pos: '관용구(전치사구)', type: 'phrase', category: 'toeic',
    meaningKo: '~을 대신하여, ~을 대표하여',
    examples: [{ en: 'I am writing this e-mail on behalf of my manager.', ko: '저는 제 매니저를 대신하여 이 이메일을 씁니다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'subject to change', ipa: '/ˈsʌb.dʒɪkt tuː tʃeɪndʒ/', pos: '관용구', type: 'phrase', category: 'toeic',
    meaningKo: '변경될 수 있는',
    examples: [{ en: 'Flight schedules are subject to change without prior notice.', ko: '항공편 일정은 사전 통지 없이 변경될 수 있다.' }],
    tip: '',
    synonyms: [], antonyms: ['fixed', 'set in stone'], collocations: [] },

  { term: 'proficiency', ipa: '/prəˈfɪʃ.ən.si/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '숙련도, 능숙함',
    examples: [{ en: 'Candidates must demonstrate proficiency in Excel.', ko: '지원자는 엑셀 숙련도를 입증해야 한다.' }],
    tip: '형용사형은 proficient. 채용 공고에서 매우 흔히 등장합니다.',
    synonyms: ['competence', 'skill'], antonyms: [], collocations: ['demonstrate proficiency'] },
  { term: 'clientele', ipa: '/ˌkliː.ənˈtel/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '고객층',
    examples: [{ en: 'The restaurant has built a loyal clientele over the years.', ko: '그 레스토랑은 수년에 걸쳐 충성도 높은 고객층을 구축했다.' }],
    tip: '"customers"보다 격식 있는 집합명사로, 특정 업체의 전체 고객층을 지칭합니다.',
    synonyms: ['customer base'], antonyms: [], collocations: ['loyal clientele'] },
  { term: 'dispatch', ipa: '/dɪˈspætʃ/', pos: '동사', type: 'word', category: 'toeic',
    meaningKo: '발송하다, 파견하다',
    examples: [{ en: 'The order will be dispatched within 24 hours.', ko: '주문은 24시간 이내에 발송될 예정이다.' }],
    tip: '물류/배송 관련 지문에서 "ship"과 유사한 의미로 자주 쓰입니다.',
    synonyms: ['send', 'ship'], antonyms: [], collocations: ['dispatch an order'] },
  { term: 'liaison', ipa: '/liˈeɪ.zɑːn/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '연락 담당자, 연계',
    examples: [{ en: 'She serves as the liaison between the marketing and sales teams.', ko: '그녀는 마케팅팀과 영업팀 사이의 연락 담당자 역할을 한다.' }],
    tip: '"liaise with"(~와 연계하다)라는 동사형으로도 자주 쓰입니다.',
    synonyms: ['contact person'], antonyms: [], collocations: ['serve as a liaison'] },
  { term: 'expedite', ipa: '/ˈek.spə.daɪt/', pos: '동사', type: 'word', category: 'toeic',
    meaningKo: '신속히 처리하다',
    examples: [{ en: 'We are expediting the shipment to meet the deadline.', ko: '마감기한을 맞추기 위해 배송을 신속히 처리하고 있다.' }],
    tip: '업무나 절차를 서둘러 처리한다는 뉘앙스로 공식 이메일에 자주 등장합니다.',
    synonyms: ['accelerate', 'speed up'], antonyms: ['delay'], collocations: ['expedite the process'] },
  { term: 'inclement', ipa: '/ɪnˈklem.ənt/', pos: '형용사', type: 'word', category: 'toeic',
    meaningKo: '(날씨가) 궂은, 악천후의',
    examples: [{ en: 'The flight was delayed due to inclement weather.', ko: '그 항공편은 악천후로 인해 지연되었다.' }],
    tip: '거의 항상 "inclement weather" 형태로만 쓰이는 고정 표현입니다.',
    synonyms: [], antonyms: ['clement', 'fair'], collocations: ['inclement weather'] },
  { term: 'amenity', ipa: '/əˈmiː.nə.ti/', pos: '명사', type: 'word', category: 'toeic',
    meaningKo: '편의시설',
    examples: [{ en: 'The hotel offers amenities such as a gym and rooftop pool.', ko: '그 호텔은 헬스장과 루프탑 수영장 같은 편의시설을 제공한다.' }],
    tip: '보통 복수형 amenities로 쓰이며, 호텔·오피스·아파트 소개 지문에 자주 등장합니다.',
    synonyms: ['facility'], antonyms: [], collocations: ['on-site amenities'] },
  { term: 'courteous', ipa: '/ˈkɝː.ti.əs/', pos: '형용사', type: 'word', category: 'toeic',
    meaningKo: '공손한, 예의 바른',
    examples: [{ en: 'The staff were courteous and attentive throughout our stay.', ko: '직원들은 저희가 머무는 내내 공손하고 세심하게 응대했다.' }],
    tip: '명사형은 courtesy(예의, 공손함).',
    synonyms: ['polite', 'considerate'], antonyms: ['rude', 'discourteous'], collocations: [] },
  { term: 'proprietary', ipa: '/prəˈpraɪ.ə.ter.i/', pos: '형용사', type: 'word', category: 'toeic',
    meaningKo: '독점적인, 소유의',
    examples: [{ en: 'The company uses a proprietary algorithm to price its products.', ko: '그 회사는 제품 가격 책정에 독점적인(자체 개발) 알고리즘을 사용한다.' }],
    tip: '외부에 공개되지 않은 자체 소유 기술/정보를 가리킬 때 씁니다.',
    synonyms: ['exclusive'], antonyms: ['open', 'public'], collocations: ['proprietary technology'] },
  { term: 'versatile', ipa: '/ˈvɝː.sə.t̬əl/', pos: '형용사', type: 'word', category: 'toeic',
    meaningKo: '다재다능한, 다용도의',
    examples: [{ en: 'This software is versatile enough to handle multiple file formats.', ko: '이 소프트웨어는 여러 파일 형식을 처리할 수 있을 만큼 다용도로 활용 가능하다.' }],
    tip: '사람과 사물(제품) 모두에 폭넓게 쓸 수 있는 형용사입니다.',
    synonyms: ['adaptable', 'flexible'], antonyms: ['limited', 'specialized'], collocations: [] },

  // ---------------- 토플 (TOEFL) ----------------
  { term: 'hypothesis', ipa: '/haɪˈpɑːθ.ə.sɪs/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '가설',
    examples: [{ en: 'The researchers tested their hypothesis through a controlled experiment.', ko: '연구자들은 통제된 실험을 통해 그들의 가설을 검증했다.' }],
    tip: '복수형은 hypotheses. 동사형은 hypothesize(가설을 세우다).',
    synonyms: ['theory', 'conjecture'], antonyms: [], collocations: ['test a hypothesis', 'propose a hypothesis'] },
  { term: 'empirical', ipa: '/ɪmˈpɪr.ɪ.kəl/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '경험적인, 실증적인',
    examples: [{ en: 'The theory lacks empirical evidence to support it.', ko: '그 이론은 이를 뒷받침할 실증적 증거가 부족하다.' }],
    tip: '',
    synonyms: [], antonyms: ['theoretical'], collocations: ['empirical evidence', 'empirical study'] },
  { term: 'phenomenon', ipa: '/fəˈnɑːm.ə.nɑːn/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '현상',
    examples: [{ en: 'Climate change is a global phenomenon affecting every continent.', ko: '기후변화는 모든 대륙에 영향을 미치는 전 지구적 현상이다.' }],
    tip: '복수형은 phenomena.',
    synonyms: [], antonyms: [], collocations: ['natural phenomenon', 'widespread phenomenon'] },
  { term: 'correlation', ipa: '/ˌkɔːr.əˈleɪ.ʃən/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '상관관계',
    examples: [{ en: 'There is a strong correlation between sleep and academic performance.', ko: '수면과 학업 성취도 사이에는 강한 상관관계가 있다.' }],
    tip: '"correlation does not imply causation"(상관관계가 인과관계를 의미하지는 않는다)이라는 표현으로 자주 등장합니다.',
    synonyms: [], antonyms: [], collocations: ['positive correlation', 'correlation between'] },
  { term: 'inherent', ipa: '/ɪnˈher.ənt/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '내재된, 고유의',
    examples: [{ en: 'There are inherent risks in any scientific experiment.', ko: '어떤 과학 실험에나 내재된 위험이 있다.' }],
    tip: '',
    synonyms: ['intrinsic', 'innate'], antonyms: [], collocations: ['inherent risk', 'inherent to'] },
  { term: 'constitute', ipa: '/ˈkɑːn.stə.tuːt/', pos: '동사', type: 'word', category: 'toefl',
    meaningKo: '구성하다, ~에 해당하다',
    examples: [{ en: 'Women constitute nearly half of the workforce in this sector.', ko: '여성은 이 분야 노동력의 거의 절반을 구성한다.' }],
    tip: '',
    synonyms: ['comprise', 'make up'], antonyms: [], collocations: [] },
  { term: 'derive', ipa: '/dɪˈraɪv/', pos: '동사', type: 'word', category: 'toefl',
    meaningKo: '(~에서) 유래하다, 도출하다',
    examples: [{ en: 'Many English words are derived from Latin.', ko: '많은 영어 단어는 라틴어에서 유래한다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: ['derive from', 'derive a conclusion'] },
  { term: 'predominant', ipa: '/prɪˈdɑː.mə.nənt/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '지배적인, 우세한',
    examples: [{ en: 'Agriculture remains the predominant industry in the region.', ko: '농업은 그 지역에서 여전히 지배적인 산업이다.' }],
    tip: '',
    synonyms: ['dominant', 'prevailing'], antonyms: [], collocations: [] },
  { term: 'subsequent', ipa: '/ˈsʌb.sə.kwənt/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '이후의, 그 다음의',
    examples: [{ en: 'The initial findings were confirmed by subsequent studies.', ko: '초기 발견은 이후 연구들에 의해 확인되었다.' }],
    tip: '',
    synonyms: [], antonyms: ['prior', 'preceding'], collocations: ['subsequent to', 'subsequent studies'] },
  { term: 'analogous', ipa: '/əˈnæl.ə.ɡəs/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '유사한, 비슷한',
    examples: [{ en: 'The structure of an atom is often described as analogous to a solar system.', ko: '원자의 구조는 흔히 태양계와 유사하다고 묘사된다.' }],
    tip: '',
    synonyms: ['similar', 'comparable'], antonyms: [], collocations: ['analogous to'] },
  { term: 'plausible', ipa: '/ˈplɑː.zə.bəl/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '그럴듯한, 타당해 보이는',
    examples: [{ en: 'The scientist offered a plausible explanation for the anomaly.', ko: '그 과학자는 그 이상현상에 대해 그럴듯한 설명을 제시했다.' }],
    tip: '',
    synonyms: [], antonyms: ['implausible'], collocations: ['plausible explanation'] },
  { term: 'ambiguous', ipa: '/æmˈbɪɡ.ju.əs/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '모호한',
    examples: [{ en: 'The instructions were ambiguous, leading to confusion among students.', ko: '지침이 모호해서 학생들 사이에 혼란이 생겼다.' }],
    tip: '',
    synonyms: [], antonyms: ['clear', 'unambiguous'], collocations: ['ambiguous wording'] },
  { term: 'controversial', ipa: '/ˌkɑːn.trəˈvɝː.ʃəl/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '논란이 되는',
    examples: [{ en: "The professor's theory remains controversial among scientists.", ko: '그 교수의 이론은 과학자들 사이에서 여전히 논란이 되고 있다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: ['controversial issue'] },
  { term: 'unprecedented', ipa: '/ʌnˈpres.ə.den.tɪd/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '전례 없는',
    examples: [{ en: 'The region experienced unprecedented levels of rainfall this year.', ko: '그 지역은 올해 전례 없는 수준의 강우량을 겪었다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: ['unprecedented growth'] },
  { term: 'sustain', ipa: '/səˈsteɪn/', pos: '동사', type: 'word', category: 'toefl',
    meaningKo: '지속시키다, 유지하다',
    examples: [{ en: 'The ecosystem cannot sustain such a rapid population increase.', ko: '그 생태계는 그렇게 급격한 개체수 증가를 지속시킬 수 없다.' }],
    tip: '',
    synonyms: ['maintain', 'uphold'], antonyms: [], collocations: ['sustain growth'] },
  { term: 'synthesis', ipa: '/ˈsɪn.θə.sɪs/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '종합, 통합, (화학) 합성',
    examples: [{ en: 'The essay presents a synthesis of several competing theories.', ko: '그 에세이는 여러 상충하는 이론들을 종합하여 제시한다.' }],
    tip: '동사형은 synthesize.',
    synonyms: [], antonyms: [], collocations: ['protein synthesis'] },
  { term: 'coherent', ipa: '/koʊˈhɪr.ənt/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '일관성 있는, 논리정연한',
    examples: [{ en: 'The student presented a coherent argument supported by evidence.', ko: '그 학생은 증거로 뒷받침된 논리정연한 주장을 제시했다.' }],
    tip: '',
    synonyms: [], antonyms: ['incoherent'], collocations: ['coherent argument'] },
  { term: 'refute', ipa: '/rɪˈfjuːt/', pos: '동사', type: 'word', category: 'toefl',
    meaningKo: '반박하다',
    examples: [{ en: 'New evidence was presented to refute the earlier claim.', ko: '이전 주장을 반박하기 위해 새로운 증거가 제시되었다.' }],
    tip: '',
    synonyms: ['rebut', 'disprove'], antonyms: ['corroborate', 'confirm'], collocations: [] },
  { term: 'in light of', ipa: '/ɪn laɪt ʌv/', pos: '관용구(전치사구)', type: 'phrase', category: 'toefl',
    meaningKo: '~을 고려하여, ~에 비추어',
    examples: [{ en: 'In light of recent findings, the theory needs to be revised.', ko: '최근 연구 결과에 비추어 그 이론은 수정될 필요가 있다.' }],
    tip: '',
    synonyms: [], antonyms: [], collocations: [] },
  { term: 'give rise to', ipa: '/ɡɪv raɪz tuː/', pos: '관용구', type: 'phrase', category: 'toefl',
    meaningKo: '~을 야기하다, 초래하다',
    examples: [{ en: 'Rapid urbanization has given rise to a number of environmental problems.', ko: '급속한 도시화는 여러 환경 문제를 야기했다.' }],
    tip: '',
    synonyms: ['lead to', 'result in'], antonyms: [], collocations: [] },
  { term: 'dichotomy', ipa: '/daɪˈkɑː.tə.mi/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '이분법, 양분',
    examples: [{ en: 'The study challenges the traditional dichotomy between nature and nurture.', ko: '그 연구는 선천성과 후천성 사이의 전통적인 이분법에 의문을 제기한다.' }],
    tip: '두 개념이 명확히 대립되는 구도를 학술적으로 표현할 때 씁니다.',
    synonyms: ['divide', 'polarity'], antonyms: [], collocations: ['false dichotomy'] },
  { term: 'proponent', ipa: '/prəˈpoʊ.nənt/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '지지자, 옹호자',
    examples: [{ en: 'She is a leading proponent of renewable energy policy.', ko: '그녀는 재생에너지 정책의 대표적인 지지자다.' }],
    tip: '반대말은 opponent(반대자).',
    synonyms: ['advocate', 'supporter'], antonyms: ['opponent', 'critic'], collocations: ['leading proponent'] },
  { term: 'skepticism', ipa: '/ˈskep.tə.sɪ.zəm/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '회의론, 의구심',
    examples: [{ en: 'The new theory was met with considerable skepticism from the scientific community.', ko: '그 새로운 이론은 과학계로부터 상당한 회의론에 부딪혔다.' }],
    tip: '형용사형은 skeptical. 학술적 비판 맥락에서 자주 등장합니다.',
    synonyms: ['doubt', 'incredulity'], antonyms: ['conviction', 'certainty'], collocations: ['meet with skepticism'] },
  { term: 'catalyst', ipa: '/ˈkæt.ə.lɪst/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '촉매, 계기',
    examples: [{ en: 'The policy change acted as a catalyst for industry-wide reform.', ko: '그 정책 변화는 업계 전반의 개혁을 촉발하는 계기로 작용했다.' }],
    tip: '화학 용어에서 유래했지만 "변화를 일으키는 계기"라는 비유적 의미로 훨씬 더 자주 쓰입니다.',
    synonyms: ['trigger', 'impetus'], antonyms: [], collocations: ['act as a catalyst'] },
  { term: 'indispensable', ipa: '/ˌɪn.dɪˈspen.sə.bəl/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '필수불가결한',
    examples: [{ en: 'Clean water is indispensable to public health.', ko: '깨끗한 물은 공중보건에 필수불가결하다.' }],
    tip: '"essential"보다 격식 있는 표현이며, "없어서는 안 될"이라는 강한 뉘앙스를 담고 있습니다.',
    synonyms: ['essential', 'vital'], antonyms: ['dispensable', 'optional'], collocations: [] },
  { term: 'momentum', ipa: '/moʊˈmen.təm/', pos: '명사', type: 'word', category: 'toefl',
    meaningKo: '추진력, 탄력',
    examples: [{ en: 'The movement gained momentum after the initial study was published.', ko: '그 운동은 초기 연구가 발표된 이후 추진력을 얻었다.' }],
    tip: '"gain/lose momentum" 형태로 물리학과 사회현상 서술 모두에 자주 쓰입니다.',
    synonyms: [], antonyms: [], collocations: ['gain momentum', 'lose momentum'] },
  { term: 'underlying', ipa: '/ˌʌn.dɚˈlaɪ.ɪŋ/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '근본적인, 기저의',
    examples: [{ en: 'Researchers are still investigating the underlying causes of the phenomenon.', ko: '연구자들은 여전히 그 현상의 근본적인 원인을 조사하고 있다.' }],
    tip: '"underlying cause/assumption/issue" 형태로 학술 글에서 매우 흔히 쓰입니다.',
    synonyms: ['fundamental', 'root'], antonyms: ['superficial'], collocations: ['underlying cause'] },
  { term: 'converge', ipa: '/kənˈvɝːdʒ/', pos: '동사', type: 'word', category: 'toefl',
    meaningKo: '수렴하다, 한 점으로 모이다',
    examples: [{ en: 'The two lines of research eventually converged on a similar conclusion.', ko: '두 연구 흐름은 결국 유사한 결론으로 수렴했다.' }],
    tip: '반대는 diverge(발산하다, 갈라지다).',
    synonyms: [], antonyms: ['diverge'], collocations: ['converge on'] },
  { term: 'counterintuitive', ipa: '/ˌkaʊn.tɚ.ɪnˈtuː.ɪ.tɪv/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '직관에 반하는',
    examples: [{ en: 'It may seem counterintuitive, but slower growth can sometimes indicate a healthier economy.', ko: '직관에 반하는 것처럼 보일 수 있지만, 성장 둔화가 때로는 더 건강한 경제를 나타내기도 한다.' }],
    tip: '예상과 다른 결과를 소개할 때 도입부에 자주 쓰이는 표현입니다.',
    synonyms: [], antonyms: ['intuitive'], collocations: [] },
  { term: 'holistic', ipa: '/hoʊˈlɪs.tɪk/', pos: '형용사', type: 'word', category: 'toefl',
    meaningKo: '전체론적인, 총체적인',
    examples: [{ en: 'The report takes a holistic approach, considering economic, social, and environmental factors together.', ko: '그 보고서는 경제·사회·환경 요인을 함께 고려하는 전체론적 접근을 취한다.' }],
    tip: '부분이 아닌 전체를 통합적으로 바라본다는 뉘앙스로, "holistic approach/view" 형태로 자주 쓰입니다.',
    synonyms: ['comprehensive', 'integrated'], antonyms: ['piecemeal', 'fragmented'], collocations: ['holistic approach'] },
];
